### ISSUE TITLE
Options for which button is used

### ISSUE THREAD

**Issue by technobly** [StuartHa/tiny_bird#3]
I was pretty excited to see this game featured in the recent Pebble email blast.  Loaded it up, and found that the UP button was too uncomfortable to play the game.  I would like to suggest just making the UP, DOWN and CENTER buttons all control the up movement as an easy fix... "PRESS ANY BUTTON".  Or add a settings menu to select which button is used, however this might not be obvious to everyone that tries the game.

FWIW: The down button is the most comfortable :)

Thanks for the game!

**Comment by StuartHa** [comment]
:star:
